promo_index:
    path:     /
    defaults: { _controller: "EuBundle:Promo:index" }
    methods:  GET

promo_show:
    path:     /show/{id}
    defaults: { _controller: "EuBundle:Promo:show" }
    methods:  GET

promo_new:
    path:     /new/{negocioId}
    defaults: { _controller: "EuBundle:Promo:new" }
    methods:  [GET, POST]

promo_edit:
    path:     /edit/{promoId}
    defaults: { _controller: "EuBundle:Promo:edit" }
    methods:  [GET, POST]

promo_delete:
    path:     /delete/{id}
    defaults: { _controller: "EuBundle:Promo:delete" }
    methods:  DELETE
