eu_negocio:
    resource: "@EuBundle/Resources/config/routing/negocio.yml"
    prefix:   /negocio

eu_homepage:
    path:     /
    defaults: { _controller: EuBundle:Default:index }

eu_promo:
    resource: "@EuBundle/Resources/config/routing/promo.yml"
    prefix:   /promo  