eu_negocio:
    resource: "@EuBundle/Resources/config/routing/negocio.yml"
    prefix:   /negocio

eu_homepage:
    path:     /insertar
    defaults: { _controller: EuBundle:EU:insert }
    methods: [POST]
    
eu_login:
    path:     /login
    defaults: { _controller: EuBundle:EU:login }    
    methods: [POST]

eu_promo:
    resource: "@EuBundle/Resources/config/routing/promo.yml"
    prefix:   /promo  
    
eu_datos:
    path:     /eu/{lang}/{uuid}
    defaults: { _controller: "EuBundle:EU:negocios", uuid:1 } 
    methods: [POST]
    requirements:
#        latitud: "[\w-]+"
#        longitud: "[\w-]+"       
        lang: es    