eu_negocio:
    resource: "@EuBundle/Resources/config/routing/negocio.yml"
    prefix:   /negocio

eu_homepage:
    path:     /
    defaults: { _controller: EuBundle:Default:index }

eu_promo:
    resource: "@EuBundle/Resources/config/routing/promo.yml"
    prefix:   /promo  
    
eu_datos:
    path:     /eu/{lang}/{uuid}
    defaults: { _controller: "EuBundle:EU:negocios", uuid:1 } 
    methods: [GET]
    requirements:
#        latitud: "[\w-]+"
#        longitud: "[\w-]+"       
        lang: es    