<?php

namespace Proxies\__CG__\EuBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Persona extends \EuBundle\Entity\Persona implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'id', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persNombre', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persDni', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persApellido', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persFecNac', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persSexo', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persDomicilio', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persFechaMod', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persAlta', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'ciudad'];
        }

        return ['__isInitialized__', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'id', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persNombre', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persDni', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persApellido', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persFecNac', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persSexo', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persDomicilio', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persFechaMod', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'persAlta', '' . "\0" . 'EuBundle\\Entity\\Persona' . "\0" . 'ciudad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Persona $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersNombre($persNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersNombre', [$persNombre]);

        return parent::setPersNombre($persNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersNombre', []);

        return parent::getPersNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersDni($persDni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersDni', [$persDni]);

        return parent::setPersDni($persDni);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersDni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersDni', []);

        return parent::getPersDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersApellido($persApellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersApellido', [$persApellido]);

        return parent::setPersApellido($persApellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersApellido', []);

        return parent::getPersApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersFecNac($persFecNac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersFecNac', [$persFecNac]);

        return parent::setPersFecNac($persFecNac);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersFecNac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersFecNac', []);

        return parent::getPersFecNac();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersSexo($persSexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersSexo', [$persSexo]);

        return parent::setPersSexo($persSexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersSexo', []);

        return parent::getPersSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersDomicilio($persDomicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersDomicilio', [$persDomicilio]);

        return parent::setPersDomicilio($persDomicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersDomicilio', []);

        return parent::getPersDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersFechaMod($persFechaMod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersFechaMod', [$persFechaMod]);

        return parent::setPersFechaMod($persFechaMod);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersFechaMod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersFechaMod', []);

        return parent::getPersFechaMod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersAlta($persAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersAlta', [$persAlta]);

        return parent::setPersAlta($persAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersAlta', []);

        return parent::getPersAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(\EuBundle\Entity\Ciudad $ciudad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

}
